FROM maven:3.9-amazoncorretto-21-alpine AS build_container

WORKDIR /build
COPY pom.xml .
RUN mvn dependency:go-offline -B

COPY  . /usr/src/build
WORKDIR /usr/src/build
RUN mvn package -B

FROM openjdk:21-slim
COPY --from=build_container /usr/src/build/target/k8s-demo-app.jar app.jar
RUN groupadd -g 1000 appuser && \
    useradd -u 1000 -g 1000 appuser
USER appuser

EXPOSE 8080/tcp
ENTRYPOINT ["java","-jar","/app.jar"]
